country_map = {
    "Bahamas, The": "Bahamas",
    "Brunei ": "Brunei",
    "Czech Republic (Czechia)": "Czechia",
    "DR Congo": "DRC",
    "Gambia, The": "Gambia",
    "Côte d'Ivoire": "Ivory Coast",
    "Cote d'Ivoire": "Ivory Coast",
    "State of Palestine": "Palestine",
    "S. Korea": "South Korea",
    "Korea, South": "South Korea",
    "Saint Barthelemy": "St. Barth",
    "St. Vincent & Grenadines": "St. Vincent Grenadines",
    "Saint Vincent and the Grenadines": "St. Vincent Grenadines",
    "Taiwan*": "Taiwan",
    "United States": "USA",
    "US": "USA",
    "United Kingdom": "UK",
    "United Arab Emirates": "UAE",
}
